defaults:
  - _self_
  - data: base
  - model: naive-pointwise
  - user_const

seed: 2024
max_steps: 2_000_000
learning_rate: 5e-5
weight_decay: 0.01
per_device_train_batch_size: 64
per_device_eval_batch_size: 6
progress_bar: False
resume_from_checkpoint: False
log_metrics: True
log_steps: 1_000

hf_hub_push: False
hf_hub_user: None
hf_hub_token: None
hf_hub_model: "uva-bert-${model.name}"

wandb_project_name: baidu-bert-hf
wandb_entity: cm-offline-metrics
