defaults:
  - _self_
  - data: base
  - model: bert
  - user_const

dataset_directory: "/beegfs/scratch/user/rdeffaye/baidu-ultr"
output_dir: "output/"
seed: 2024
learning_rate: 5e-5
max_steps: 2_000_000
weight_decay: 0.01
per_device_train_batch_size: 64
progress_bar: False
resume_from_checkpoint: False
log_metrics: True

wandb_project_name: baidu-bert-model
wandb_entity: cm-offline-metrics
